addons:
  sonarcloud:
    organization: azak-azkaran-github
    token:
      secure: DG/mubA8SCyhwnEnlbUoLWivUN7vt5bDqFJmFEWy2xtupSu9zWyOqqegc0MqP3DhYukFyqnxrBsysytmsncChZdyz8E7maaEJdm7uybKhsaxaLOIIw6yV7sa8dLanMoWuMY+0yM52mJ6gaQZ5Iz2xt166eWifNVYwZ8FEGaEik1FRizVUAzk0AWVwpJQS5713RoJt5iOC3IwG65CTDhPUh15HROSYL2Gg6mw7dY4VpIXamFG8adhpQMfL11KxV5NRo5fe6CEt7wd0csABVL37PMOjLvRaGY4v/bJOddiz/xNdJVgEDjDUOFEN6BEkkqaPfw4OopOBqi+Xk8Sd0HnYWDbHD8HdlmJLiHTBNttnrPSx8PUkKlj51XBkASbaLzqY1uY6J8Phb8x0fQQ1MELV+APuJkOJHW8iX+Oh2mhgGg1YxJEf5gzh+QjzZ3cSdzUQG+LYUNEjh5ATaKgjrqw31w53afXDPBxHZXwMiWV0ZrF94SAd7iBNd8njhEW6b/33DoGharKp6/jBKRnajxorYuqL61v6qN7cqtaWMbF/M2jR/f1KWU1i2Qs6p0EfzoME68fGSH54OHBt3oLoUoBIw/eaDmJPyNrr4cRU16zrQxeNRhv7jwlItSW42hUaB916r8tpUNhDDHq9ktSDckq82p8DrzNyIKEHf2Nu7VwnCc=
env:
  global:
  - secure: iRvFadlRLZFuf9HIt3eAo63ddg0Ogf0cLjg1j+tW0/6n6Xjto7sr9xes/PpHlg2JlNTzzMU0+qKz0of8XtllAwcI4ERmT1bZLbm4xW13PbZ4ERZR5IzQtDgwRWIm/ejK0DFGAN5gdyn6W3rNW8F9nzC94FfvsjojwLqXQxVFRotShd0lRPHjvTdYVYElCu/AygDJm99CEjZOlGDWmYxBjLtfx+OQuUFxdMIzJAPYPav/in0x+nJmcEw4lY+C5kTqtd62+ESIg0esF0hfg/OIFeLrgwNOJcEpJZr0qAVO1+E8tgyTmKF7ZhQiQh+dDKOq0c3YDSPd+uuXmKiwnGyqcGI3XYoKgnIxSgMuLYLDI8nMiH8Yfo6gd3EFMLPN4Wn7GWKdI5pg2r5l8X0DRF/YtnJOrCg9yphb7h5upihOz4yjBMuw5hq4CIHRA0lgTur0ZQmGJoCXL1XS1Oro4SZUKsRgCCY+ynFNIRYxo/Ti+gcDBGc40YNxKgKIClOjt4q+scpW7odytMPGhFjB24rNTSVvjICvbvkMSHJYC/9GG3vS+qLVyK9VTRGVwyLdpfHqL5jernnlGumwF4+jtYXx7S5fRwUZOMSdjvpA+aLun4sMcuCW4y7CIm6YJmE4qqKlpoAiCg6nrocF5x4tsSqXffuBk7T/g3EOCOmIOsJwFf4=
language: go
sudo: false
go:
- tip
before_install:
- sudo apt-get update
- sudo apt-get install findutils
script:
- go get ./...
- go test -v -coverprofile=cover.out
- go test -json > report.json
- sonar-scanner
